openapi: 3.0.1
info:
  title: STD2032 TD-Final-Part1
  description: API for managing football competitions, teams, and players.
  version: 1.0.0

servers:
  - url: https://STD23032.football-competition.com

paths:
  /competitions:
    get:
      summary: Get the list of competitions
      parameters:
        - in: query
          name: page
          schema:
            type: integer
          required: true
          description: The page number.
        - in: query
          name: pageSize
          schema:
            type: integer
          required: true
          description: The number of items per page.
      responses:
        "200":
          description: A paginated list of competitions.
          content:
            application/json:
              schema:
                $ref: "#/components/schemas/PaginatedCompetitions"

    post:
      summary: Create a new competition
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: "#/components/schemas/Competition"
      responses:
        "201":
          description: Competition created successfully.

  /teams:
    get:
      summary: Get a list of teams
      parameters:
        - in: query
          name: teamName
          schema:
            type: string
          description: Filter teams by name.
        - in: query
          name: page
          schema:
            type: integer
          required: true
          description: The page number.
        - in: query
          name: pageSize
          schema:
            type: integer
          required: true
          description: The number of items per page.
      responses:
        '200':
          description: A paginated list of teams.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedTeams'

    post:
      summary: Create a new team
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Team'
      responses:
        '201':
          description: Team created successfully.

  /teams/{teamId}/players:
    get:
      summary: Get a list of players in a team
      parameters:
        - in: path
          name: teamId
          schema:
            type: integer
          required: true
          description: The ID of the team.
        - in: query
          name: playerName
          schema:
            type: string
          description: Filter players by name.
        - in: query
          name: page
          schema:
            type: integer
          required: true
          description: The page number.
        - in: query
          name: pageSize
          schema:
            type: integer
          required: true
          description: The number of items per page.
      responses:
        '200':
          description: A paginated list of players.
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaginatedPlayers'
